---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cidr-filtering
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cidr-filtering
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cidr-filtering
subjects:
- kind: ServiceAccount
  name: cidr-filtering
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cidr-filtering
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cidr-filtering-cni-ds
  namespace: kube-system
  labels:
    tier: node
    app: cidr-filtering-cni
    name: cidr-filtering-cni
spec:
  selector:
    matchLabels:
      name: cidr-filtering-cni
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: cidr-filtering-cni
        name: cidr-filtering-cni
    spec:
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      serviceAccountName: cidr-filtering
      initContainers:
      - name: cidr-filtering-cni-copier
        image: registry.access.redhat.com/ubi8/ubi:8.6-754
        env:
        - name: CNI_NAME
          value: cidr-filtering-cni
        - name: CNI_CONF_DIR
          value: "/host/etc/cni/net.d"
        - name: SCRIPT
          value: "IyEvYmluL2Jhc2gKCnNldCAtZXVvIHBpcGVmYWlsCgpzdGRpbj0kKGNhdCAvZGV2L3N0ZGluKQpsb2dGaWxlPSIke0xPR0ZJTEU6LS92YXIvbG9nL2NpZHItZmlsdGVyaW5nLWNuaS5sb2d9IgoKZXhlYyAyPj4gJGxvZ0ZpbGUKCk5GVF9UQUJMRV9ORVRERVY9bmV0ZGV2Ck5GVF9UQUJMRV9CUklER0U9YnJpZGdlCk5GVF9UQUJMRT1maWx0ZXIKCk5GVF9JTkdSRVNTX0NIQUlOPWluZ3Jlc3MKTkZUX0lOR1JFU1NfSE9PSz1pbmdyZXNzCgpORlRfUE9TVFJPVVRJTkdfQ0hBSU49cG9zdHJvdXRpbmcKTkZUX0VHUkVTU19IT09LPXBvc3Ryb3V0aW5nCgpnZXRfb2JqZWN0KCkgewogICAgbG9jYWwganNvbl9vYmplY3Q9IiQxIgogICAgbG9jYWwganNvbl9wYXRoPSIkMiIKICAgIGVjaG8gIiRqc29uX29iamVjdCIgfCBqcSAtY3IgIiRqc29uX3BhdGgiCn0KCmdldF9hcnJheV9pdGVtcygpIHsKICAgIGxvY2FsIGpzb25fb2JqZWN0PSIkMSIKICAgIGxvY2FsIGpzb25fcGF0aD0iJDIiCiAgICBlY2hvICIkanNvbl9vYmplY3QiIHwganEgLWMgJGpzb25fcGF0aCB8IGpxIC1jciAiLltdIgp9CgpnZXRfYXJyYXlfbGVuKCkgewogICAgbG9jYWwganNvbl9vYmplY3Q9IiQxIgogICAgbG9jYWwganNvbl9wYXRoPSIkMiIKICAgIGVjaG8gIiRqc29uX29iamVjdCIgfCBqcSAtYyAiJGpzb25fcGF0aCIgfCBqcSAiLiB8IGxlbmd0aCIKfQoKZm9yX2pzb25fYXJyYXkoKSB7CiAgICBsb2NhbCBqc29uX29iamVjdD0iJDEiCiAgICBsb2NhbCBqc29uX3BhdGg9IiQyIgogICAgbG9jYWwgZm49IiQzIgogICAgZm9yIGl0ZW0gaW4gJChnZXRfYXJyYXlfaXRlbXMgIiRqc29uX29iamVjdCIgIiRqc29uX3BhdGgiKTsgZG8KICAgICAgICAkZm4gJGl0ZW0KICAgIGRvbmUKfQoKZ2V0X2lwX3ZlcnNpb24oKSB7CiAgICBsb2NhbCBpcF9hZGRyZXNzPSIkMSIKICAgIGlmIFtbICIkaXBfYWRkcmVzcyIgPX4gLio6LiogXV0KICAgIHRoZW4KICAgICAgICBlY2hvICJpcDYiCiAgICBlbHNlCiAgICAgICAgZWNobyAiaXAiCiAgICBmaQp9CgpjcmVhdGVfdGFibGUoKSB7CiAgICBsb2NhbCB0eXBlPSIkMSIKICAgIGxvY2FsIG5hbWU9IiQyIgogICAgZWNobyAibmZ0IGFkZCB0YWJsZSAkdHlwZSAkbmFtZSIgfCB0ZWUgLWEgJGxvZ0ZpbGUKfQoKY3JlYXRlX25ldGRldl9iYXNlX2NoYWluKCkgewogICAgbG9jYWwgdHlwZT0iJDEiCiAgICBsb2NhbCBuYW1lPSIkMiIKICAgIGxvY2FsIGNoYWluPSIkMyIKICAgIGxvY2FsIGhvb2s9IiQ0IgogICAgbG9jYWwgZGV2aWNlPSIkNSIKICAgIGVjaG8gIm5mdCBhZGQgY2hhaW4gJHR5cGUgJG5hbWUgJGNoYWluIHsgdHlwZSBmaWx0ZXIgaG9vayAkaG9vayBkZXZpY2UgJGRldmljZSBwcmlvcml0eSAwOyBwb2xpY3kgYWNjZXB0OyB9IiB8IHRlZSAtYSAkbG9nRmlsZQp9CgpjcmVhdGVfYmFzZV9jaGFpbigpIHsKICAgIGxvY2FsIHR5cGU9IiQxIgogICAgbG9jYWwgbmFtZT0iJDIiCiAgICBsb2NhbCBjaGFpbj0iJDMiCiAgICBsb2NhbCBob29rPSIkNCIKICAgIGVjaG8gIm5mdCBhZGQgY2hhaW4gJHR5cGUgJG5hbWUgJGNoYWluIHsgdHlwZSBmaWx0ZXIgaG9vayAkaG9vayBwcmlvcml0eSAwOyBwb2xpY3kgYWNjZXB0OyB9IiB8IHRlZSAtYSAkbG9nRmlsZQp9CgpjcmVhdGVfY2hhaW4oKSB7CiAgICBsb2NhbCB0eXBlPSIkMSIKICAgIGxvY2FsIG5hbWU9IiQyIgogICAgbG9jYWwgY2hhaW49IiQzIgogICAgZWNobyAibmZ0IGFkZCBjaGFpbiAkdHlwZSAkbmFtZSAkY2hhaW4iIHwgdGVlIC1hICRsb2dGaWxlCn0KCm5mdF9hZGRfcnVsZSgpIHsKICAgIGxvY2FsIHR5cGU9IiQxIgogICAgbG9jYWwgdGFibGU9IiQyIgogICAgbG9jYWwgY2hhaW49IiQzIgogICAgc2V0IC0tICIke0A6NH0iCiAgICBlY2hvICJuZnQgYWRkIHJ1bGUgJHR5cGUgJHRhYmxlICRjaGFpbiAkQCIgfCB0ZWUgLWEgJGxvZ0ZpbGUKfQoKY3JlYXRlX3J1bGVzX2Zvcl9maWx0ZXJpbmcoKSB7CiAgICBsb2NhbCBwb2xpY3lfaWQ9IiQxIgogICAgbG9jYWwgdGFibGVfdHlwZT0iJDIiCiAgICBsb2NhbCBkaXJlY3Rpb249IiQzIgogICAgbG9jYWwgbWF0Y2hfaWZhY2U9IiQ0IgogICAgCiAgICBsb2NhbCBtYXRjaF9hZGRyPSJzYWRkciIKICAgIGlmIFtbICIkZGlyZWN0aW9uIiA9PSAiZWdyZXNzIiBdXTsgdGhlbgogICAgICAgIGxvY2FsIG1hdGNoX2FkZHI9ImRhZGRyIgogICAgZmkKICAgIAogICAgX2NyZWF0ZV9zdWJuZXRfcnVsZSgpIHsKICAgICAgICBsb2NhbCBzdWJuZXQ9JDEKICAgICAgICBpZiBbWyAiJChnZXRfb2JqZWN0ICIke3N1Ym5ldH0iICIuc3VibmV0LmV4Y2VwdCIpIiAhPSAibnVsbCIgXV07IHRoZW4KICAgICAgICAgICAgZm9yX2pzb25fYXJyYXkgIiR7c3VibmV0fSIgIi5zdWJuZXQuZXhjZXB0IiBfZHJvcF9pcAogICAgICAgIGZpCgogICAgICAgIGlmIFtbICIkKGdldF9vYmplY3QgIiR7c3VibmV0fSIgIi5zdWJuZXQuY2lkciIpIiA9PSAibnVsbCIgXV07IHRoZW4KICAgICAgICAgICAgZXhpdFdpdGhFcnJvciAiY2lkciBtdXN0IGJlIHNwZWNpZmllZC4iCiAgICAgICAgZmkKICAgICAgICBfYWNjZXB0X2NpZHIgIiR7c3VibmV0fSIKICAgIH0KCiAgICBfZHJvcF9pcCgpIHsKICAgICAgICBsb2NhbCBpcD0iJDEiCiAgICAgICAgaXAgbmV0bnMgZXhlYyAiJENOSV9DT05UQUlORVJJRCIgJChuZnRfYWRkX3J1bGUgJHt0YWJsZV90eXBlfSAke05GVF9UQUJMRX0gbS0ke3BvbGljeV9pZH0tJHtkaXJlY3Rpb259LXN1Ym5ldHMgJHttYXRjaF9pZmFjZX0gJENOSV9JRk5BTUUgJChnZXRfaXBfdmVyc2lvbiAiJHtpcH0iKSAke21hdGNoX2FkZHJ9ICIke2lwfSIgY291bnRlciBkcm9wKQogICAgfQoKICAgIF9hY2NlcHRfY2lkcigpIHsKICAgICAgICBsb2NhbCBzdWJuZXQ9IiQxIgogICAgICAgIGxvY2FsIGNpZHI9JChlY2hvICIke3N1Ym5ldH0iIHwganEgLXIgIi5zdWJuZXQuY2lkciIpCiAgICAgICAgaXAgbmV0bnMgZXhlYyAiJENOSV9DT05UQUlORVJJRCIgJChuZnRfYWRkX3J1bGUgJHt0YWJsZV90eXBlfSAke05GVF9UQUJMRX0gbS0ke3BvbGljeV9pZH0tJHtkaXJlY3Rpb259LXN1Ym5ldHMgJHttYXRjaF9pZmFjZX0gJENOSV9JRk5BTUUgJChnZXRfaXBfdmVyc2lvbiAiJHtjaWRyfSIpICR7bWF0Y2hfYWRkcn0gIiR7Y2lkcn0iIGNvdW50ZXIgbWV0YSBtYXJrIHNldCBtYXJrIG9yIDB4MjAwMDApCiAgICB9CgogICAgX2FjY2VwdF9wb3J0KCkgewogICAgICAgIGxvY2FsIHBvcnRzPSIkMSIKICAgICAgICBsb2NhbCBwb3J0PSQoZWNobyAiJHBvcnRzIiB8IGpxIC1yICIucG9ydCIpCiAgICAgICAgbG9jYWwgcHJvdG9jb2w9JChlY2hvICIkcG9ydHMiIHwganEgLXIgIi5wcm90b2NvbCIpCgogICAgICAgIGlmIFtbICIkcG9ydCIgPT0gIm51bGwiIHx8ICIkcHJvdG9jb2wiID09ICJudWxsIiB8fCAiJHBvcnQiID09ICIiIHx8ICIkcHJvdG9jb2wiID09ICIiIF1dOyB0aGVuCiAgICAgICAgICAgIGV4aXRXaXRoRXJyb3IgIlBvcnQgYW5kIHByb3RvY29sIG11c3QgYmUgc3BlY2lmaWVkLiIKICAgICAgICBlbHNlCiAgICAgICAgICAgIGlwIG5ldG5zIGV4ZWMgIiRDTklfQ09OVEFJTkVSSUQiICQobmZ0X2FkZF9ydWxlICR7dGFibGVfdHlwZX0gJHtORlRfVEFCTEV9IG0tJHtwb2xpY3lfaWR9LSR7ZGlyZWN0aW9ufS1wb3J0cyAke21hdGNoX2lmYWNlfSAkQ05JX0lGTkFNRSAke3Byb3RvY29sLCx9IGRwb3J0ICR7cG9ydH0gY291bnRlciBtZXRhIG1hcmsgc2V0IG1ldGEgbWFyayAifCIgMHgwMDAxMDAwMCkKICAgICAgICBmaQogICAgfQoKICAgICMgaGFuZGxlIGlwIGJsb2NrCiAgICBpZiBbWyAkKGVjaG8gIiRzdGRpbiIgfCBqcSAtciAiLiR7ZGlyZWN0aW9ufS5zdWJuZXRzIikgIT0gIm51bGwiIF1dOyB0aGVuCiAgICAgICAgZm9yX2pzb25fYXJyYXkgIiRzdGRpbiIgIi4ke2RpcmVjdGlvbn0uc3VibmV0cyIgX2NyZWF0ZV9zdWJuZXRfcnVsZQogICAgZmkKCiAgICAjIGhhbmRsZSBwb3J0cwogICAgaWYgW1sgJChlY2hvICIkc3RkaW4iIHwganEgLXIgIi4ke2RpcmVjdGlvbn0ucG9ydHMiKSAhPSAibnVsbCIgXV07IHRoZW4KICAgICAgICBmb3JfanNvbl9hcnJheSAiJHN0ZGluIiAiLiR7ZGlyZWN0aW9ufS5wb3J0cyIgX2FjY2VwdF9wb3J0CiAgICBmaQp9CgpleGl0V2l0aEVycm9yKCkgewogICAgZWNobyAieyJjbmlWZXJzaW9uIjogIiQoanEgLXIgIi5jbmlWZXJzaW9uIiA8PDwgIiRzdGRpbiIpIiwibXNnIjoiJDEiLCJjb2RlIjoxMDEsImRldGFpbHMiOiIkMiJ9IgogICAgZXhpdCAxCn0KCmV4aXRXaXRoU3VjY2VzcygpIHsKICAgIHByZXZfcmVzdWx0PSQoZ2V0X29iamVjdCAiJHtzdGRpbn0iICIucHJldlJlc3VsdCIpCiAgICBpZiBbWyAiJHByZXZfcmVzdWx0IiA9PSAibnVsbCIgXV07IHRoZW4KICAgICAgICBlY2hvICJ7ImNuaVZlcnNpb24iOiAiJChqcSAtciAiLmNuaVZlcnNpb24iIDw8PCAiJHN0ZGluIikifSIKICAgIGVsc2UKICAgICAgICBlY2hvICIkcHJldl9yZXN1bHQiCiAgICBmaQogICAgZXhpdCAwCn0KCmNyZWF0ZV9jaGFpbnNfZm9yX2ZpbHRlcmluZygpIHsKICAgIGxvY2FsIHBvbGljeV9pZD0iJDEiCiAgICBsb2NhbCB0YWJsZV90eXBlPSIkMiIKICAgIGxvY2FsIGRpcmVjdGlvbj0iJDMiCgogICAgbG9jYWwgbWF0Y2hfaWZhY2U9ImlpZm5hbWUiCiAgICBpZiBbWyAiJGRpcmVjdGlvbiIgPT0gImVncmVzcyIgXV07IHRoZW4KICAgICAgICBtYXRjaF9pZmFjZT0ib2lmbmFtZSIKICAgIGZpCgogICAgaXAgbmV0bnMgZXhlYyAiJENOSV9DT05UQUlORVJJRCIgJChjcmVhdGVfY2hhaW4gIiR7dGFibGVfdHlwZX0iICIke05GVF9UQUJMRX0iIG0tIiR7cG9saWN5X2lkfSItIiR7ZGlyZWN0aW9ufSIpIHx8IGV4aXRXaXRoRXJyb3IgIkZhaWxlZCB0byBhZGQgY2hhaW4gbS0ke3BvbGljeV9pZH0tJHtkaXJlY3Rpb259IgogICAgaXAgbmV0bnMgZXhlYyAiJENOSV9DT05UQUlORVJJRCIgJChuZnRfYWRkX3J1bGUgIiR7dGFibGVfdHlwZX0iICIke05GVF9UQUJMRX0iIG0tIiR7ZGlyZWN0aW9ufSIgIiR7bWF0Y2hfaWZhY2V9IiAiJENOSV9JRk5BTUUiIGNvdW50ZXIganVtcCBtLSIke3BvbGljeV9pZH0iLSIke2RpcmVjdGlvbn0iKSB8fCBleGl0V2l0aEVycm9yICJGYWlsZWQgdG8gYWRkIHJ1bGU6IGp1bXAgbS0ke3BvbGljeV9pZH0tJHtkaXJlY3Rpb259IgoKICAgIGlwIG5ldG5zIGV4ZWMgIiRDTklfQ09OVEFJTkVSSUQiICQoY3JlYXRlX2NoYWluICIke3RhYmxlX3R5cGV9IiAiJHtORlRfVEFCTEV9IiBtLSIke3BvbGljeV9pZH0iLSIke2RpcmVjdGlvbn0iLXN1Ym5ldHMpIHx8IGV4aXRXaXRoRXJyb3IgIkZhaWxlZCB0byBhZGQgY2hhaW4gbS0iJHtwb2xpY3lfaWR9Ii0iJHtkaXJlY3Rpb259Ii1zdWJuZXRzIgogICAgaXAgbmV0bnMgZXhlYyAiJENOSV9DT05UQUlORVJJRCIgJChjcmVhdGVfY2hhaW4gIiR7dGFibGVfdHlwZX0iICIke05GVF9UQUJMRX0iIG0tIiR7cG9saWN5X2lkfSItIiR7ZGlyZWN0aW9ufSItcG9ydHMpIHx8IGV4aXRXaXRoRXJyb3IgIkZhaWxlZCB0byBhZGQgY2hhaW4gbS0iJHtwb2xpY3lfaWR9Ii0iJHtkaXJlY3Rpb259Ii1wb3J0cyIKICAgIAogICAgaXAgbmV0bnMgZXhlYyAiJENOSV9DT05UQUlORVJJRCIgJChuZnRfYWRkX3J1bGUgIiR7dGFibGVfdHlwZX0iICIke05GVF9UQUJMRX0iIG0tIiR7cG9saWN5X2lkfSItIiR7ZGlyZWN0aW9ufSIgY291bnRlciBqdW1wIG0tIiR7cG9saWN5X2lkfSItIiR7ZGlyZWN0aW9ufSItc3VibmV0cykgfHwgZXhpdFdpdGhFcnJvciAiRmFpbGVkIHRvIGFkZCBydWxlOiBqdW1wIG0tIiR7cG9saWN5X2lkfSItIiR7ZGlyZWN0aW9ufSItc3VibmV0cyIKICAgIGlwIG5ldG5zIGV4ZWMgIiRDTklfQ09OVEFJTkVSSUQiICQobmZ0X2FkZF9ydWxlICIke3RhYmxlX3R5cGV9IiAiJHtORlRfVEFCTEV9IiBtLSIke3BvbGljeV9pZH0iLSIke2RpcmVjdGlvbn0iIGNvdW50ZXIganVtcCBtLSIke3BvbGljeV9pZH0iLSIke2RpcmVjdGlvbn0iLXBvcnRzKSB8fCBleGl0V2l0aEVycm9yICJGYWlsZWQgdG8gYWRkIHJ1bGU6IGp1bXAgbS0iJHtwb2xpY3lfaWR9Ii0iJHtkaXJlY3Rpb259Ii1wb3J0cyIKCiAgICBjcmVhdGVfcnVsZXNfZm9yX2ZpbHRlcmluZyAiJHtwb2xpY3lfaWR9IiAiJHt0YWJsZV90eXBlfSIgIiR7ZGlyZWN0aW9ufSIgIiR7bWF0Y2hfaWZhY2V9Igp9CgptYWluKCkgewogICAgY2FzZSAkQ05JX0NPTU1BTkQgaW4KICAgIEFERCkKICAgICAgICBlY2hvICJDTklfTkVUTlM6ICRDTklfTkVUTlMiID4+ICRsb2dGaWxlCiAgICAgICAgZWNobyAiQ05JX0NPTlRBSU5FUklEOiAkQ05JX0NPTlRBSU5FUklEIiA+PiAkbG9nRmlsZQogICAgICAgIGVjaG8gIlNURElOOiAkc3RkaW4iID4+ICRsb2dGaWxlCgogICAgICAgIGxvY2FsIHBvbGljeV9uYW1lPSQoZWNobyAiJHN0ZGluIiB8IGpxIC1yICIubmFtZSIpCiAgICAgICAgbG9jYWwgcG9saWN5X2lkPSIkKGVjaG8gIiRwb2xpY3lfbmFtZSIgfCBzaGExc3VtICkiCiAgICAgICAgcG9saWN5X2lkPSIke3BvbGljeV9pZDowOjV9IiAjIHVzZSBmaXJzdCA1IGNoYXJhY3RlcnMgdG8gaWRlbnRpZnkgYSBwb2xpY3kKCiAgICAgICAgbWtkaXIgLXAgL3Zhci9ydW4vbmV0bnMvCiAgICAgICAgbG4gLXNmVCAiJENOSV9ORVROUyIgL3Zhci9ydW4vbmV0bnMvIiR7Q05JX0NPTlRBSU5FUklEfSIKCiAgICAgICAgaXAgbmV0bnMgZXhlYyAiJENOSV9DT05UQUlORVJJRCIgJChjcmVhdGVfdGFibGUgJHtORlRfVEFCTEVfQlJJREdFfSAke05GVF9UQUJMRX0pIHx8IGV4aXRXaXRoRXJyb3IgIkZhaWxlZCB0byBjcmVhdGUgdGFibGUgJHtORlRfVEFCTEVfQlJJREdFfSAke05GVF9UQUJMRX0iCiAgICAgICAgaXAgbmV0bnMgZXhlYyAiJENOSV9DT05UQUlORVJJRCIgJChjcmVhdGVfdGFibGUgJHtORlRfVEFCTEVfTkVUREVWfSAke05GVF9UQUJMRX0pIHx8IGV4aXRXaXRoRXJyb3IgIkZhaWxlZCB0byBjcmVhdGUgdGFibGUgJHtORlRfVEFCTEVfQlJJREdFfSAke05GVF9UQUJMRX0iCgogICAgICAgICMgY3JlYXRlIGJhc2UgY2hhaW5zCiAgICAgICAgaXAgbmV0bnMgZXhlYyAiJENOSV9DT05UQUlORVJJRCIgJChjcmVhdGVfbmV0ZGV2X2Jhc2VfY2hhaW4gJHtORlRfVEFCTEVfTkVUREVWfSAke05GVF9UQUJMRX0gJHtORlRfSU5HUkVTU19DSEFJTn0gJHtORlRfSU5HUkVTU19IT09LfSAke0NOSV9JRk5BTUV9KSB8fCBleGl0V2l0aEVycm9yICJGYWlsZWQgdG8gY3JlYXRlIG5ldGRldiBiYXNlIGNoYWluICR7TkZUX0lOR1JFU1NfQ0hBSU59IgogICAgICAgIGlwIG5ldG5zIGV4ZWMgIiRDTklfQ09OVEFJTkVSSUQiICQoY3JlYXRlX2Jhc2VfY2hhaW4gJHtORlRfVEFCTEVfQlJJREdFfSAke05GVF9UQUJMRX0gJHtORlRfUE9TVFJPVVRJTkdfQ0hBSU59ICR7TkZUX0VHUkVTU19IT09LfSkgfHwgZXhpdFdpdGhFcnJvciAiRmFpbGVkIHRvIGNyZWF0ZSBicmlkZ2UgYmFzZSBjaGFpbiAke05GVF9QT1NUUk9VVElOR19DSEFJTn0iCgogICAgICAgICMgZmlsdGVyIGNoYWlucwogICAgICAgIGlwIG5ldG5zIGV4ZWMgIiRDTklfQ09OVEFJTkVSSUQiICQoY3JlYXRlX2NoYWluICR7TkZUX1RBQkxFX05FVERFVn0gJHtORlRfVEFCTEV9IG0taW5ncmVzcykgfHwgZXhpdFdpdGhFcnJvciAiRmFpbGVkIHRvIGFkZCBjaGFpbiBtLWluZ3Jlc3MiCiAgICAgICAgaXAgbmV0bnMgZXhlYyAiJENOSV9DT05UQUlORVJJRCIgJChjcmVhdGVfY2hhaW4gJHtORlRfVEFCTEVfQlJJREdFfSAke05GVF9UQUJMRX0gbS1lZ3Jlc3MpIHx8IGV4aXRXaXRoRXJyb3IgIkZhaWxlZCB0byBhZGQgY2hhaW4gbS1lZ3Jlc3MiCgogICAgICAgICMgc2V0dXAgcHJlcm91dGluZyBjaGFpbgogICAgICAgIGlwIG5ldG5zIGV4ZWMgIiRDTklfQ09OVEFJTkVSSUQiICQobmZ0X2FkZF9ydWxlICR7TkZUX1RBQkxFX05FVERFVn0gJHtORlRfVEFCTEV9ICR7TkZUX0lOR1JFU1NfQ0hBSU59IGV0aGVyIHR5cGUgYXJwIGNvdW50ZXIgYWNjZXB0KSB8fCBleGl0V2l0aEVycm9yICJGYWlsZWQgdG8gYWxsb3cgYXJwIGZvciBpbmdyZXNzIgogICAgICAgIGlwIG5ldG5zIGV4ZWMgIiRDTklfQ09OVEFJTkVSSUQiICQobmZ0X2FkZF9ydWxlICR7TkZUX1RBQkxFX05FVERFVn0gJHtORlRfVEFCTEV9ICR7TkZUX0lOR1JFU1NfQ0hBSU59IGlpZm5hbWUgJENOSV9JRk5BTUUgY291bnRlciBqdW1wIG0taW5ncmVzcykgfHwgZXhpdFdpdGhFcnJvciAiRmFpbGVkIHRvIGFkZCBydWxlOiBqdW1wIG0taW5ncmVzcyIKCiAgICAgICAgIyBzZXR1cCBwb3N0cm91dGluZyBjaGFpbgogICAgICAgIGlwIG5ldG5zIGV4ZWMgIiRDTklfQ09OVEFJTkVSSUQiICQobmZ0X2FkZF9ydWxlICR7TkZUX1RBQkxFX0JSSURHRX0gJHtORlRfVEFCTEV9ICR7TkZUX1BPU1RST1VUSU5HX0NIQUlOfSBldGhlciB0eXBlIGFycCBjb3VudGVyIGFjY2VwdCkgfHwgZXhpdFdpdGhFcnJvciAiRmFpbGVkIHRvIGFsbG93IGFycCBmb3IgZWdyZXNzIgogICAgICAgIGlwIG5ldG5zIGV4ZWMgIiRDTklfQ09OVEFJTkVSSUQiICQobmZ0X2FkZF9ydWxlICR7TkZUX1RBQkxFX0JSSURHRX0gJHtORlRfVEFCTEV9ICR7TkZUX1BPU1RST1VUSU5HX0NIQUlOfSBvaWZuYW1lICRDTklfSUZOQU1FIGNvdW50ZXIganVtcCBtLWVncmVzcykgfHwgZXhpdFdpdGhFcnJvciAiRmFpbGVkIHRvIGFkZCBydWxlOiBqdW1wIG0tZWdyZXNzIgoKICAgICAgICBpcCBuZXRucyBleGVjICIkQ05JX0NPTlRBSU5FUklEIiAkKG5mdF9hZGRfcnVsZSAiJHtORlRfVEFCTEVfTkVUREVWfSIgIiR7TkZUX1RBQkxFfSIgbS1pbmdyZXNzIGNvdW50ZXIgbWV0YSBtYXJrIHNldCBtZXRhIG1hcmsgIiYiIDB4ZmZmY2ZmZmYpIHx8IGV4aXRXaXRoRXJyb3IgIkZhaWxlZCB0byBhZGQgcnVsZTogc2V0IG1ldGEgbWFyayAmIDB4ZmZmY2ZmZmYiCiAgICAgICAgaXAgbmV0bnMgZXhlYyAiJENOSV9DT05UQUlORVJJRCIgJChuZnRfYWRkX3J1bGUgIiR7TkZUX1RBQkxFX0JSSURHRX0iICIke05GVF9UQUJMRX0iIG0tZWdyZXNzIGNvdW50ZXIgbWV0YSBtYXJrIHNldCBtZXRhIG1hcmsgIiYiIDB4ZmZmY2ZmZmYpIHx8IGV4aXRXaXRoRXJyb3IgIkZhaWxlZCB0byBhZGQgcnVsZTogc2V0IG1ldGEgbWFyayAmIDB4ZmZmY2ZmZmYiCgogICAgICAgIGNyZWF0ZV9jaGFpbnNfZm9yX2ZpbHRlcmluZyAkcG9saWN5X2lkICR7TkZUX1RBQkxFX05FVERFVn0gImluZ3Jlc3MiCiAgICAgICAgY3JlYXRlX2NoYWluc19mb3JfZmlsdGVyaW5nICRwb2xpY3lfaWQgJHtORlRfVEFCTEVfQlJJREdFfSAiZWdyZXNzIgoKICAgICAgICBpcCBuZXRucyBleGVjICIkQ05JX0NPTlRBSU5FUklEIiAkKG5mdF9hZGRfcnVsZSAiJHtORlRfVEFCTEVfTkVUREVWfSIgIiR7TkZUX1RBQkxFfSIgbS1pbmdyZXNzIG1ldGEgbWFyayAiJiIgMHgwMDAzMDAwMCA9PSAweDAwMDMwMDAwIGNvdW50ZXIgcmV0dXJuKSB8fCBleGl0V2l0aEVycm9yICJGYWlsZWQgdG8gYWRkIHJ1bGU6IG1hcmsgJiAweDAwMDMwMDAwID09IDB4MDAwMzAwMDAgY291bnRlciByZXR1cm4iCiAgICAgICAgaXAgbmV0bnMgZXhlYyAiJENOSV9DT05UQUlORVJJRCIgJChuZnRfYWRkX3J1bGUgIiR7TkZUX1RBQkxFX05FVERFVn0iICIke05GVF9UQUJMRX0iIG0taW5ncmVzcyBjb3VudGVyIGRyb3ApIHx8IGV4aXRXaXRoRXJyb3IgIkZhaWxlZCB0byBhZGQgcnVsZTogZHJvcCIKCiAgICAgICAgaXAgbmV0bnMgZXhlYyAiJENOSV9DT05UQUlORVJJRCIgJChuZnRfYWRkX3J1bGUgIiR7TkZUX1RBQkxFX0JSSURHRX0iICIke05GVF9UQUJMRX0iIG0tZWdyZXNzIG1ldGEgbWFyayAiJiIgMHgwMDAzMDAwMCA9PSAweDAwMDMwMDAwIGNvdW50ZXIgcmV0dXJuKSB8fCBleGl0V2l0aEVycm9yICJGYWlsZWQgdG8gYWRkIHJ1bGU6IG1hcmsgJiAweDAwMDMwMDAwID09IDB4MDAwMzAwMDAgY291bnRlciByZXR1cm4iCiAgICAgICAgaXAgbmV0bnMgZXhlYyAiJENOSV9DT05UQUlORVJJRCIgJChuZnRfYWRkX3J1bGUgIiR7TkZUX1RBQkxFX0JSSURHRX0iICIke05GVF9UQUJMRX0iIG0tZWdyZXNzIGNvdW50ZXIgZHJvcCkgfHwgZXhpdFdpdGhFcnJvciAiRmFpbGVkIHRvIGFkZCBydWxlOiBkcm9wIgoKICAgICAgICBleGl0V2l0aFN1Y2Nlc3MKICAgIDs7CgogICAgREVMKQogICAgICAgIGVjaG8gIkRlbGV0ZSAkQ05JX0NPTlRBSU5FUklEIiA+PiAkbG9nRmlsZQogICAgICAgIHJtIC1mIC92YXIvcnVuL25ldG5zLyIkQ05JX0NPTlRBSU5FUklEIgogICAgOzsKCiAgICBWRVJTSU9OKQogICAgICAgIGVjaG8gInsiY25pVmVyc2lvbiI6IjAuMy4xIiwic3VwcG9ydGVkVmVyc2lvbnMiOlsiMC4xLjAiLCIwLjIuMCIsIjAuMy4wIiwiMC4zLjEiXX0iCiAgICA7OwoKICAgICopCiAgICAgICAgZXhpdFdpdGhFcnJvciAiVW5yZWNvZ25pemVkIENOSSBjb21tYW5kOiAke0NOSV9DT01NQU5EfSIKICAgIDs7CgogICAgZXNhYwp9CgptYWluCg=="
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
        command:
          - /bin/bash
          - -c
          - |
            echo $(SCRIPT) | base64 -d > /host/opt/cni/bin/$(CNI_NAME) &&\
            chmod +x /host/opt/cni/bin/$(CNI_NAME)

            # Inspired by: https://tinyurl.com/y7r2knme
            CIDR_TEMP_KUBECONFIG="/tmp/cidr-filtering.kubeconfig"
            CIDR_KUBECONFIG_FILE_HOST=$(CNI_CONF_DIR)/cidr-filtering.d/cidr-filtering.kubeconfig
            mkdir -p $(CNI_CONF_DIR)/cidr-filtering.d
            

            SERVICE_ACCOUNT_PATH=/var/run/secrets/kubernetes.io/serviceaccount
            KUBE_CA_FILE=${KUBE_CA_FILE:-$SERVICE_ACCOUNT_PATH/ca.crt}
            SERVICEACCOUNT_TOKEN=$(cat $SERVICE_ACCOUNT_PATH/token)
            SKIP_TLS_VERIFY=${SKIP_TLS_VERIFY:-false}

            # Check if we're running as a k8s pod.
            if [ -f "$SERVICE_ACCOUNT_PATH/token" ]; then
              # We're running as a k8d pod - expect some variables.
              if [ -z ${KUBERNETES_SERVICE_HOST} ]; then
                error "KUBERNETES_SERVICE_HOST not set"; exit 1;
              fi
              if [ -z ${KUBERNETES_SERVICE_PORT} ]; then
                error "KUBERNETES_SERVICE_PORT not set"; exit 1;
              fi

              if [ "$SKIP_TLS_VERIFY" == "true" ]; then
                TLS_CFG="insecure-skip-tls-verify: true"
              elif [ -f "$KUBE_CA_FILE" ]; then
                TLS_CFG="certificate-authority-data: $(cat $KUBE_CA_FILE | base64 | tr -d '\n')"
              fi

              # Write a kubeconfig file for the CNI plugin.  Do this
              # to skip TLS verification for now.  We should eventually support
              # writing more complete kubeconfig files. This is only used
              # if the provided CNI network config references it.
              touch $CIDR_TEMP_KUBECONFIG
              chmod ${KUBECONFIG_MODE:-600} $CIDR_TEMP_KUBECONFIG
              # Write the kubeconfig to a temp file first.
              cat > $CIDR_TEMP_KUBECONFIG <<EOF
            # Kubeconfig file for CIDR CNI plugin.
            apiVersion: v1
            kind: Config
            clusters:
            - name: local
              cluster:
                server: ${KUBERNETES_SERVICE_PROTOCOL:-https}://[${KUBERNETES_SERVICE_HOST}]:${KUBERNETES_SERVICE_PORT}
                $TLS_CFG
            users:
            - name: cidr-filtering
              user:
                token: "${SERVICEACCOUNT_TOKEN}"
            contexts:
            - name: cidr-filtering-context
              context:
                cluster: local
                user: cidr-filtering
            current-context: cidr-filtering-context
            EOF

              # Atomically move the temp kubeconfig to its permanent home.
              mv -f $CIDR_TEMP_KUBECONFIG $CIDR_KUBECONFIG_FILE_HOST
            else
              warn "Doesn't look like we're running in a kubernetes environment (no serviceaccount token)"
            fi
      containers:
      - name: cidr-filtering-cni
        image: registry.access.redhat.com/ubi8/ubi:8.6-754
        command: ["sleep"]
        args: ["infinity"]
        resources:
          requests:
            cpu: "10m"
            memory: "25Mi"
          limits:
            cpu: "10m"
            memory: "25Mi"
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cni
        hostPath:
          path: /etc/cni/net.d
      - name: cnibin
        hostPath:
          path: /opt/cni/bin
