---
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-network
  namespace: default
  labels:
    cidr-filtering-cni: ""
data:
  config.json: |
    {
      "ingress": {
        "subnets": [
          {
            "subnet": {
              "cidr": "192.168.66.0/24",
              "except": [
                "192.168.66.105"
              ]
            }
          }
        ]
      },
      "egress": {
        "subnets": [
          {
            "subnet": {
              "cidr": "192.168.66.0/24",
              "except": [
                "192.168.66.105"
              ]
            }
          }
        ]
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: network-dhcp
  namespace: default
  labels:
    cidr-filtering-cni: ""
data:
  config.json: |
    {
      "egress": {
        "subnets": [
          {
            "subnet": {
              "cidr": "255.255.255.255/32",
              "except": []
            }
          }
        ]
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: google-dns
  namespace: default
  labels:
    cidr-filtering-cni: ""
data:
  config.json: |
    {
      "ingress": {
        "subnets": [
          {
            "subnet": {
              "cidr": "8.8.4.4/24",
              "except": [
                "8.8.4.5"
              ]
            }
          }
        ]
      },
      "egress": {
        "subnets": [
          {
            "subnet": {
              "cidr": "8.8.4.4/24"
            }
          }
        ]
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: all-ports
  namespace: default
  labels:
    cidr-filtering-cni: ""
data:
  config.json: |
    {
      "ingress": {
        "ports": [
          {
          "protocol": "TCP",
            "port": "1-65535"
          },
          {
          "protocol": "udp",
            "port": "1-65535"
          }
        ]
      },
      "egress": {
        "ports": [
          {
            "protocol": "TCP",
            "port": "1-65535"
          },
          {
            "protocol": "udp",
            "port": "1-65535"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: a-configmapped-network
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "nad-bridge-cidr",
    "plugins": [
      {
        "type": "cnv-bridge",
        "bridge": "br1"
      },
      {
        "type": "cidr-filtering-cni",
        "label": "cidr-filtering-cni"
      }
    ]
  }'